name: CI Back-end
on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - 'sgcmapi/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Compile/Test
        working-directory: sgcmapi/
        run: mvn compile test
